import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Editorial Standards, Sources and Corrections",
  description: "Who publishes Business Debt Insider, how to interpret our sources and examples, our commercial interests, and how to request a correction.",
  alternates: { canonical: "/editorial-policy" },
};
export default function EditorialPolicy() {
  return <article className="mx-auto max-w-content px-6 py-14 md:py-20">
    <div className="max-w-3xl space-y-9 text-base md:text-lg leading-relaxed">
      <header><p className="font-mono text-xs uppercase tracking-wider text-muted">Editorial standards</p><h1 className="mt-3 text-4xl md:text-5xl font-bold tracking-tight">Who publishes our guidance—and how to evaluate it.</h1><p className="mt-5">Business Debt Insider publishes information about commercial debt and operates a financial consulting practice. Readers should be able to distinguish general education, a worked example, and a proposal for their own business.</p></header>
      <section><h2 className="text-2xl font-semibold">Publisher and authorship</h2><p className="mt-4">Business Debt Insider is a trade name of GRL Recovery LLC, based in Fort Lauderdale, Florida. Articles carrying the Business Debt Insider byline are attributed to the organization. Some older content used the TerraDebt Team label; those organization bylines now display the current brand.</p><p className="mt-4">We do not currently publish individual author or reviewer biographies. An organization byline does not mean an article has been reviewed by an attorney, accountant, or other licensed professional. BDI is not a law firm or lender.</p></section>
      <section><h2 className="text-2xl font-semibold">Sources and the limits of a summary</h2><p className="mt-4">Statutes, court resources, regulators, and tax agencies are the primary references for legal and regulatory topics. Where a page summarizes a particular rule, the relevant official source should appear with the discussion. The source&apos;s jurisdiction, date, and scope matter.</p><p className="mt-4">A further-reading list offers background; it is not evidence that every statement in an article has been independently verified. An enforcement case involving one provider does not describe every provider. A rule for consumer debt, one state, or one type of financing should not be assumed to cover all commercial transactions.</p></section>
      <section><h2 className="text-2xl font-semibold">Examples and performance claims</h2><p className="mt-4">Illustrative calculations should identify their assumptions and be labeled as hypothetical. They are not client results, fee quotes, predictions, or guarantees. A lower periodic payment should not be presented as a reduction in total cost unless the complete figures support it.</p><p className="mt-4">A published client outcome should have supporting records and appropriate publication permission. An average or success rate should identify the period, sample, fees, exclusions, and calculation. A testimonial alone cannot establish what another business will achieve. See <Link href="/trust" className="text-pine underline">our transparency page</Link> for questions to ask about an engagement.</p></section>
      <section><h2 className="text-2xl font-semibold">Commercial interests and comparisons</h2><p className="mt-4">BDI may benefit when readers request a consultation and engage its services. We are not an independent consumer organization. Our company comparisons include our own program, and that interest is disclosed on the comparison pages. Consult the linked public records and other perspectives before selecting a provider.</p><p className="mt-4">A link to a government agency or another organization does not mean that organization endorses BDI. Ratings and complaints can change, and readers should check the original record when making a decision.</p></section>
      <section><h2 className="text-2xl font-semibold">Dates, corrections, and professional advice</h2><p className="mt-4">A publication date describes when an article was published; it is not a promise that every legal rule remains unchanged. Where a source-check date is shown, it identifies that check, not a professional review of your circumstances.</p><p className="mt-4">To request a correction, send the page URL, the passage in question, and the supporting source through our <Link href="/contact" className="text-pine underline">contact page</Link>. Do not send account credentials or confidential court documents in an editorial message.</p><p className="mt-4">For advice about a contract, deadline, court matter, credit consequence, or tax liability, consult a qualified professional who can review your documents. Submitting a BDI form does not extend a deadline or create an attorney-client relationship.</p></section>
    </div>
  </article>;
}
